name: Continuous Delivery (CD)

on:
  push:
    branches: ["master"]

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env
          echo "GATEWAY_SECRET=${{ secrets.GATEWAY_SECRET }}" >> .env
          echo "SERVICE_SECRET=${{ secrets.SERVICE_SECRET }}" >> .env

      - name: stop containers
        run: docker compose down -v

      - name: Pull new images
        run: docker compose pull || true

      - name: Start Docker services
        run: docker compose up -d --build